version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/aludvik/ergo
    steps:
      - checkout
      - run: if [[ $(go fmt) ]]; then exit 1; else exit 0; fi
      - run: go vet
      - run: go test -v
